/// Flutter icons BioIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BioIcons
///      fonts:
///       - asset: fonts/BioIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BioIcons {
  BioIcons._();

  static const _kFontFam = 'BioIcons';
  static const String? _kFontPkg = null;

  static const IconData github = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
